module.exports = {
  DISCORD_TOKEN: process.env.DISCORD_TOKEN || 'YOUR_DISCORD_BOT_TOKEN_HERE',
  DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID || 'YOUR_DISCORD_CLIENT_ID_HERE',
  OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY || 'YOUR_OPENROUTER_API_KEY_HERE'
}; 